language: python

python:
  - "3.6.5"

install:
  - pip install -r requirements.txt
  - pip install codecov httmock pycodestyle pylint pytest pytest-cov

script:
  - python -m pycodestyle --max-line-length=119 .
  - python -m pylint *.py pyzoopla
  - python -m pytest --cov=pyzoopla --durations=5 tests/

after_success:
  - codecov
